# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
books = Book.create(title: "Tintin, Le Lotus bleu", description:"Dans Le Lotus bleu (1936) Tintin s'engage à démanteler le trafic d'opium international qui sévit dans un pays mythique certes, mais dont il ignore tout, la Chine. À l'aube de ce récit, la généreuse ambition de Tintin semble démesurée. Aidé par la seule société secrète, Les Fils du Dragon, et par son ami Tchang, rencontré tardivement, il parvient à surmonter tous les obstacles et ruiner les perfides machinations de ses nombreux ennemis.", poster_url:"https://cdn001.tintin.com/public/tintin/img/albums/tintin/le-lotus-bleu-fr.png", author:"Hergé", isbn:"9780316358569")
books = Book.create(title: "Le Silmarillion", description:"La Quenta Silmarillion relate l'histoire d'Arda de la première guerre entre les Valar et Melkor jusqu'à la fin du Premier Âge du Soleil, lorsque ce dernier est rejeté dans le Vide Extérieur. Le nom du texte provient des Silmarils, trois joyaux prodigieux façonnés par l'Elfe Fëanor et dérobés par Melkor (alias Morgoth).", poster_url: "https://images.epagine.fr/410/9782267017410_1_75.jpg", author:"J. R. R. Tolkien", isbn:"9780261102446")
books = Book.create(title: "La nuit des temps", description:"Une expédition en exploration au Pôle Sud détecte des signaux perçus avec un appareil de sondage sous glaciaire. Les scientifiques découvrent alors une cité souterraine, à 900 mètres de profondeur, issue d'une civilisation datant vraisemblablement de 900 000 ans.", poster_url: "https://images-na.ssl-images-amazon.com/images/I/418Y25Z5JQL._SX283_BO1,204,203,200_.jpg", author: "René Barjavel", isbn:"9782266023030")
books = Book.create(title: "Le rouge et le Noir", description:"Fils de charpentier, Julien Sorel est trop sensible et trop ambitieux pour suivre la carrière familiale dans la scierie d'une petite ville de province. Julien trouve une place de précepteur dans la maison du maire, Monsieur de Rénal, et noue une relation interdite avec son épouse.", poster_url: "http://www.culturel.tn/medias/couver2/9782070412396.jpg", author: "Stendhal", isbn:"9782070412396")
books = Book.create(title: "Les fourmis", description:"Le livre est divisé en deux univers distincts, qui finissent par se recouper à la fin du récit : le monde des humains et celui des fourmis. Ce dernier est lui-même divisé en deux histoires parallèles : celle de la vie de la soldate et celle de la vie de la nouvelle reine.", poster_url: "https://static.fnac-static.com/multimedia/Images/FR/NR/88/ff/03/262024/1540-1/tsp20200506070124/Les-Fourmis-Les-Fourmis-Tome-1.jpg", author:"Bernard Werber", isbn:"9782253063339")
books = Book.create(title: "La fille de Brooklyn", description:"L'histoire d'amour d'un père célibataire et d'une jeune fille abimée par la vie qui veut par-dessus tout rester discrète. Convaincu qu'ils ont été subitement séparés à cause des fantômes du passé qu'il a réveillés, Raphaël part à la recherche d'Anna avec l'aide de son ami Marc.", poster_url: "https://static.fnac-static.com/multimedia/Images/FR/NR/7d/fb/81/8518525/1540-1/tsp20181003154440/La-Fille-de-Brooklyn.jpg", author:"Guillaume Musso", isbn:"9782266275149")
books = Book.create(title: "Da Vinci Code", description:"Robert Langdon, un symbologue américain, est entraîné malgré lui, lors d'un voyage à Paris, dans l'affaire du meurtre de Jacques Saunière, conservateur au Musée du Louvre. ... Seule Sophie Neveu, cryptologue et petite-fille de Saunière, croit en l'innocence de l'Américain.", poster_url: "https://images-na.ssl-images-amazon.com/images/I/A15FFg6aNLL.jpg", author: "Dan Brown", isbn:"9782266198356")
books = Book.create(title: "Demon Slayer: Kimetsu no Yaiba, Vol.1", description:"Un jeune vendeur de charbon nommé Tanjiro mène une vie sans histoire dans les montagnes, jusqu'au jour tragique où il découvre son village et sa famille massacrés par un démon. ... Afin de renverser le processus et de venger sa famille, Tanjiro décide de partir en quête de vérité.", poster_url: "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/8/83/Kimetsu_no_Yaiba_V1.png/revision/latest?cb=20200630173203&path-prefix=fr", author:"Koyoharu Gotouge", isbn:"9781974700523")
books = Book.create(title: "One piece - Tome 1", description:"Nous sommes à l'ère des pirates. Lufy, un garçon espiègle, rêve de devenir le roi des pirates en trouvant le One Piece, un fabuleux trésor. ... Avec l'aide de ses précieux amis, dont le fidèle Shanks, il va devoir affronter de redoutables pirates dans des aventures toujours plus rocambolesques.", poster_url: "https://www.glenat.com/sites/default/files/images/livres/couv/9782723488525-T.jpg", author:"Eiichiro Oda", isbn:"9780575078680")
books = Book.create(title: "Jujutsu Kaisen - Tome 1", description:"Yuji Itadori est une étudiante lambda, membre du club de spiritisme, il ne croit pas une seule seconde aux fantômes... jusqu'à ce qu'une mission tourne mal à cause d'une relique ancienne d'une puissance inégalable. Yuji va se retrouver au coeur d'une aventure surréaliste.", poster_url: "https://images-na.ssl-images-amazon.com/images/I/71+HW7-kq2L.jpg", author: "Gege Akutami", isbn:"9781974710027")
books = Book.create(title: "Tokyo Revengers - Tome 1", description:"À 26 ans, Takemichi a le sentiment d'avoir déjà raté sa vie. ... Encore sous le choc, Takemichi est à son tour victime d'un accident qui le ramène inexplicablement 12 ans en arrière, lorsqu'il était au collège et se donnait des airs de mauvais garçon.", poster_url: "https://www.glenat.com/sites/default/files/images/livres/couv/9782344035290-001-T.jpeg", author: "Ken Wakui", isbn:"9788834904954")
books = Book.create(title: "L'Alchimiste", description:"Santiago, un jeune berger andalou, part à la recherche d'un trésor enfoui au pied des Pyramides. Lorsqu'il rencontre l'Alchimiste dans le désert, celui-ci lui apprend à écouter son cœur, à lire les signes du destin et, par-dessus tout, à aller au bout de son rêve.", poster_url: "https://editions.flammarion.com/media/cache/couverture_large/flammarion_img/Couvertures/9782081394704.jpg", author: "Paulo Coelho", isbn:"9782253150909")
books = Book.create(title: "Harry Potter - Tome 1 - Harry Potter à l'école des sorciers", description:"Harry Potter est un garçon ordinaire. Mais le jour de ses onze ans, son existence bascule : un géant vient le chercher pour l'emmener dans une école de sorciers.", poster_url: "https://products-images.di-static.com/image/j-k-rowling-harry-potter-tome-1-harry-potter-a-l-ecole-des-sorciers/9782070624522-475x500-1.jpg", author: "J.K.Rowling", isbn:"9782070541270")
books = Book.create(title: "XIII - Tome & : XIII - Le Jour du soleil noir", description:"Un amnésique est recueilli et soigné par un couple de retraités, Abe et Martha. Il a un XIII tatoué sur la clavicule. ... Son seul début d'indice pour découvrir son identité est un chiffre, XIII, qu'il porte en tatouage. Sa position est d'autant plus inconfortable qu'une bande de tueurs est à ses trousses.", poster_url: "https://bdi.dlpdomain.com/album/9782505067573/couv/M650x809/xiii-tome-1-le-jour-du-soleil-noir.jpg", author:"Jean Van Hamme", isbn:"9782871294504")
books = Book.create(title: "Lanfeust De Troy - Tome 1 - L'ivoire du Magohamoth", description:"Troy est un monde fascinant, où la magie intervient dans le quotidien de tous. Chacun en effet possède un pouvoir, petit ou grand, plus ou moins utile. L'un à le don de figer l'eau en glace, l'autre le pouvoir d'émettre des pets colorés...", poster_url: "https://images-na.ssl-images-amazon.com/images/I/81RG9yCekAL.jpg", author: "Didier Tarquin, Christophe Arleston", isbn:"9782302052109")
books = Book.create(title: "Astérix - Tome 1 - Astérix le Gaulois", description:"Un village peuplé d'irréductibles Gaulois résiste encore et toujours à l'envahisseur. Dans un petit village d' Armorique, Astérix va s'adonner à son sport favori : la Chasse. Pendant ce temps, les romains, tente de résoudre le mystère de la puissance des gaulois.", poster_url: "https://www.bdfugue.com/media/catalog/product/cache/1/image/400x/17f82f742ffe127f42dca9de82fb58b1/9/7/9782012101333_1_75.jpg", author:"Albert Uderzo, René Goscinny", isbn:"9782012101333")